### ISSUE TITLE
hand joints reprojection error

### ISSUE THREAD

**Issue by ligengen** [facebookresearch/hot3d#20]
Hi authors,

Thank you for your work!

I noticed some issues in the dataset. In the initial frames of a sequence, the ground truth data seems to have errors. When I reproject the 3D MANO joints onto the image, the discrepancies are significant. However, after around 20 frames, the reprojections align perfectly. Could this be an issue with the hand data or the camera pose? I would greatly appreciate any insights you can offer.

e.g. In P0014_6db96fd0, red for left-hand joints and green for right-hand joints. I show the first 100 frames. 

https://github.com/user-attachments/assets/1a70f4fd-36c8-4fc1-884d-537f8b499afb

The same is true for other sequences like P0003_c701bd11.

https://github.com/user-attachments/assets/f5e47ed8-3e3c-4c98-b45a-3b11f515ce4b

**Comment by SeaOtocinclus** [comment]
Hello, thank you for reporting and illustrating the issue.
We are aware of this issue and provide to our user a masking logic https://github.com/facebookresearch/hot3d?tab=readme-ov-file#using-mask-files (see mask and code API to load them)

In this case, you want to load the `mask_qa_pass.csv` file and you will see it is set to false for that short time range, indicating that our QA process identified those frames are invalid from a data perspective.

**Comment by ligengen** [comment]
@SeaOtocinclus Thanks for your reply!
Is it possible to release a mask file for hand pose accuracy only?

**Comment by SeaOtocinclus** [comment]
`mask_qa_pass` is a global mask; a conservative estimate. So yes, it will exclude some potential HAND data that could be valid, because a segment of data has been set as invalid for another reason (object tracking).

What you can do is to only ignore frames at the start of a sequence, the most likely synchronization issue is only happening at sequences beginning, so it could be a safe bet for you to just ignore some frames on each sequence start.
